Version = 0
ID = "00000000-0000-0000-0000-000000000000"
Name = "sample"
PropertiesSchema = "properties_schema.json"
HashType = "sha2-256"
RequiresVersion = 7

[Properties]
  description = "a bogus test holochain"
  language = "en"

[BasedOn]

[[Zomes]]
  Name = "zySampleZome"
  Description = "this is a zygomas test zome"
  Code = "zySampleZome.zy"
  NucleusType = "zygo"
  [Zomes.CodeHash]

  [[Zomes.Entries]]
    Name = "evenNumbers"
    DataFormat = "zygo"
    Schema = ""
    Sharing = "public"
    [Zomes.Entries.SchemaHash]

  [[Zomes.Entries]]
    Name = "primes"
    DataFormat = "json"
    Schema = ""
    Sharing = "public"
    [Zomes.Entries.SchemaHash]

  [[Zomes.Entries]]
    Name = "profile"
    DataFormat = "json"
    Schema = "profile.json"
    Sharing = "public"
    [Zomes.Entries.SchemaHash]

  [[Zomes.Functions]]
    Name = "getDNA"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "addEven"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "addPrime"
    CallingType = "json"

  [[Zomes.Functions]]
    Name = "testStrFn1"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "testStrFn2"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "testJsonFn1"
    CallingType = "json"

  [[Zomes.Functions]]
    Name = "testJsonFn2"
    CallingType = "json"

[[Zomes]]
  Name = "jsSampleZome"
  Description = "this is a javascript test zome"
  Code = "jsSampleZome.js"
  NucleusType = "js"
  [Zomes.CodeHash]

  [[Zomes.Entries]]
    Name = "oddNumbers"
    DataFormat = "js"
    Schema = ""
    Sharing = "public"
    [Zomes.Entries.SchemaHash]

  [[Zomes.Entries]]
    Name = "profile"
    DataFormat = "json"
    Schema = "profile.json"
    Sharing = "public"
    [Zomes.Entries.SchemaHash]

  [[Zomes.Entries]]
    Name = "rating"
    DataFormat = "links"
    Schema = ""
    Sharing = ""
    [Zomes.Entries.SchemaHash]

  [[Zomes.Functions]]
    Name = "getProperty"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "addOdd"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "addProfile"
    CallingType = "json"

  [[Zomes.Functions]]
    Name = "testStrFn1"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "testStrFn2"
    CallingType = "string"

  [[Zomes.Functions]]
    Name = "testJsonFn1"
    CallingType = "json"

  [[Zomes.Functions]]
    Name = "testJsonFn2"
    CallingType = "json"
